name: Build and Push Docker Images to GHCR

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase image owner
      id: vars
      run: |
        echo "owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and Push Frontend Image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/frontend:latest ./frontend
        docker push ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/frontend:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/backend:latest ./backend
        docker push ghcr.io/${{ steps.vars.outputs.owner_lowercase }}/backend:latest
