name: Build and Push Docker Images to GHCR

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend
        docker push ghcr.io/${{ github.repository_owner }}/backend:latest
